//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype_Fixes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prototype_Fixes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.UI.Colors
        ///Windows.UI.ColorHelper
        ///Windows.UI.Text.CaretType
        ///Windows.UI.Text.FindOptions
        ///Windows.UI.Text.FontStretch
        ///Windows.UI.Text.FontStyle
        ///Windows.UI.Text.FontWeight
        ///Windows.UI.Text.FormatEffect
        ///Windows.UI.Text.HorizontalCharacterAlignment
        ///Windows.UI.Text.IRichEditTextRange
        ///Windows.UI.Text.ITextCharacterFormat
        ///Windows.UI.Text.ITextDocument
        ///Windows.UI.Text.ITextParagraphFormat
        ///Windows.UI.Text.ITextRange
        ///Windows.UI.Text.ITextSelection
        ///Windows.UI.Text.LetterCase
        ///Windows.UI.Text.LineSp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string validNames {
            get {
                return ResourceManager.GetString("validNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Namespace should be updated to Microsoft.
        /// </summary>
        public static string WUX_Using_Description {
            get {
                return ResourceManager.GetString("WUX_Using_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Windows Namespace instead of Microsoft.
        /// </summary>
        public static string WUX_Using_MessageFormat {
            get {
                return ResourceManager.GetString("WUX_Using_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Namespace should be Microsoft.
        /// </summary>
        public static string WUX_Using_Title {
            get {
                return ResourceManager.GetString("WUX_Using_Title", resourceCulture);
            }
        }
    }
}
